## First Lab -> Numpy

In [1]:
!pip3 install numpy

In [2]:
import numpy as np

- This will Directly store in C++ (8bit per interger instent of 28 bit in python)

In [3]:
print(np.array([10,20,30])) 

[10 20 30]


In [5]:
a1 = np.array([10,20,30])
a2 = np.array([[2,3],[4,5]])

a2

array([[2, 3],
       [4, 5]])

In [6]:
a3 = np.array([1,2,3,4,5,6])

In [7]:
a3

array([1, 2, 3, 4, 5, 6])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
a4 = np.ones((4,4),dtype=int)

In [15]:
a5 = a4.reshape(2,8)
a5

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [16]:
import random

In [17]:
np.random.randint(0,100,(3,3))

array([[88, 38, 64],
       [ 2, 24, 60],
       [31, 98, 57]])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.linspace(10,1000,5)

array([  10. ,  257.5,  505. ,  752.5, 1000. ])

In [21]:
l3 = []
for i in range(3):
    l3.append(5+i)
l3

[5, 6, 7]

In [22]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1+a2
a1*a2
a2-a1
a2/a

array([5, 7, 9])